# .streamlit/secrets.toml

UPSTOX_API_KEY = "4da5cafc-0077-4069-96fa-b4e6c675a509"
UPSTOX_ACCESS_TOKEN = "eyJ0eXAiOiJKV1QiLCJrZXlfaWQiOiJza192MS4wIiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiI1SkI4QzgiLCJqdGkiOiI2ODgxYzJmZjZmNGMyOTdjYWM1YTFiODIiLCJpc011bHRpQ2xpZW50IjpmYWxzZSwiaXNQbHVzUGxhbiI6dHJ1ZSwiaWF0IjoxNzUzMzM0NTI3LCJpc3MiOiJ1ZGFwaS1nYXRld2F5LXNlcnZpY2UiLCJleHAiOjE3NTMzOTQ0MDB9.0CPcOnsEewNMJ3P4kW71Vq6MhrM4TD2KISDdmAMqCS4"
