# .streamlit/secrets.toml

UPSTOX_API_KEY = "4da5cafc-0077-4069-96fa-b4e6c675a509"
UPSTOX_ACCESS_TOKEN = "eyJ0eXAiOiJKV1QiLCJrZXlfaWQiOiJza192MS4wIiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiI1SkI4QzgiLCJqdGkiOiI2ODgwZjYwZmM3ZTA3YzdmODdhZDU2YzUiLCJpc011bHRpQ2xpZW50IjpmYWxzZSwiaXNQbHVzUGxhbiI6dHJ1ZSwiaWF0IjoxNzUzMjgyMDYzLCJpc3MiOiJ1ZGFwaS1nYXRld2F5LXNlcnZpY2UiLCJleHAiOjE3NTMzMDgwMDB9.RFA9j-ale--wjwfSAAB0T1CHI18MdAIAPgVMV_ieh64"
