# .streamlit/secrets.toml

UPSTOX_API_KEY = "4da5cafc-0077-4069-96fa-b4e6c675a509"
UPSTOX_ACCESS_TOKEN = "eyJ0eXAiOiJKV1QiLCJrZXlfaWQiOiJza192MS4wIiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiI1SkI4QzgiLCJqdGkiOiI2ODgxZTg5NjQ4ZGMzODE0ZTRhM2ZlOGEiLCJpc011bHRpQ2xpZW50IjpmYWxzZSwiaXNQbHVzUGxhbiI6dHJ1ZSwiaWF0IjoxNzUzMzQ0MTUwLCJpc3MiOiJ1ZGFwaS1nYXRld2F5LXNlcnZpY2UiLCJleHAiOjE3NTMzOTQ0MDB9.SEZSKHfaBb6HdsyxfpJVuFc5dAdP_M3EKyq7h7dSSVY"
