# .streamlit/secrets.toml

UPSTOX_API_KEY = "4da5cafc-0077-4069-96fa-b4e6c675a509"
UPSTOX_ACCESS_TOKEN = "eyJ0eXAiOiJKV1QiLCJrZXlfaWQiOiJza192MS4wIiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiI1SkI4QzgiLCJqdGkiOiI2ODgwN2Y2NDFjOTZlMjZlMWUxMjdhMGMiLCJpc011bHRpQ2xpZW50IjpmYWxzZSwiaXNQbHVzUGxhbiI6dHJ1ZSwiaWF0IjoxNzUzMjUxNjg0LCJpc3MiOiJ1ZGFwaS1nYXRld2F5LXNlcnZpY2UiLCJleHAiOjE3NTMzMDgwMDB9.YfhgFJqUuexjGuNT73BEtJLDkUx_kmTigpHS4difF1o"
