# .streamlit/secrets.toml

UPSTOX_API_KEY = "4da5cafc-0077-4069-96fa-b4e6c675a509"
UPSTOX_ACCESS_TOKEN = "eyJ0eXAiOiJKV1QiLCJrZXlfaWQiOiJza192MS4wIiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiI1SkI4QzgiLCJqdGkiOiI2ODgxYWY2MzZmNGMyOTdjYWM1YTE3YTUiLCJpc011bHRpQ2xpZW50IjpmYWxzZSwiaXNQbHVzUGxhbiI6dHJ1ZSwiaWF0IjoxNzUzMzI5NTA3LCJpc3MiOiJ1ZGFwaS1nYXRld2F5LXNlcnZpY2UiLCJleHAiOjE3NTMzOTQ0MDB9.6P75DA8mAJCtfYvXHnrBj-Q2-V_Ld4rjsRiwwgVXv30"
